PhysicalModel:
  wheelbase: 2.5          # Distance between front and rear axles (in meters)
  mass: 1500.0            # Mass of the vehicle (in kg)
  inertia: 2500.0         # Inertia around yaw axis (in kg*m^2)

Actuation:
  max_torque_throttle: 400.0   # Maximum torque for throttle (in Nm)
  max_torque_brake: 500.0      # Maximum torque for braking (in Nm)
  max_steering: 0.5            # Maximum steering angle (in radians)
  steering_resolution: 0.01    # Resolution for steering (in radians)
  throttle_resolution: 1.0     # Resolution for throttle (in Nm)
  brake_resolution: 1.0        # Resolution for brake (in Nm)

IMU:
  noise_std_ax: 0.1            # Standard deviation of acceleration noise in X direction (in m/s^2)
  noise_std_ay: 0.1            # Standard deviation of acceleration noise in Y direction (in m/s^2)
  noise_std_yaw: 0.01          # Standard deviation of yaw rate noise (in rad/s)
